# version: 0.0
# os: ubuntu
# files:
#   # - source: /
#   #   destination: /home/ec2-user/express-app
#   - source: /index.html
#     destination: /home/ubuntu/
# hooks:
#   # ApplicationStop:
#   #   - location: scripts/application_stop.sh
#   #     timeout: 300
#   #     runas: ec2-user
#   BeforeInstall:
#     - location: scripts/before_install.sh
#       timeout: 300
#       # runas: ec2-user
#       runas: ubuntu
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       # runas: ec2-user
#       runas: ubuntu

version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/express-app
hooks:
 ApplicationStop:
   - location: scripts/application_stop.sh
     timeout: 300
     runas: ec2-user
 BeforeInstall:
   - location: scripts/before_install.sh
     timeout: 300
     runas: ec2-user
 ApplicationStart:
   - location: scripts/application_start.sh
     timeout: 300
     runas: ec2-user
